name: freakwan_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.4

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
